"""scoring_engine_ip_columns

Revision ID: 72a3190412ba
Revises: 001
Create Date: 2026-06-24 16:48:51.579109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '72a3190412ba'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canonical_scores', sa.Column('score_ci_lower', sa.Numeric(), nullable=True))
    op.add_column('canonical_scores', sa.Column('score_ci_upper', sa.Numeric(), nullable=True))
    op.add_column('canonical_scores', sa.Column('score_velocity_6h', sa.Numeric(), nullable=True))
    op.add_column('canonical_scores', sa.Column('score_velocity_24h', sa.Numeric(), nullable=True))
    op.add_column('canonical_scores', sa.Column('score_velocity_48h', sa.Numeric(), nullable=True))
    op.add_column('canonical_scores', sa.Column('ensemble_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('canonical_scores', sa.Column('compound_flag', sa.Boolean(), nullable=True))
    op.add_column('canonical_scores', sa.Column('regulatory_fingerprint', sa.Text(), nullable=True))
    # These indexes may or may not exist depending on whether TimescaleDB is installed
    conn = op.get_bind()
    for idx in [
        'canonical_scores_scored_at_idx',
        'idx_scores_cell_hazard',
        'idx_locations_customer',
        'idx_flood_features_cell',
        'ml_features_flood_observed_at_idx',
        'ml_features_heat_observed_at_idx',
        'ml_features_wildfire_observed_at_idx',
        'idx_obs_cell_hazard_time',
    ]:
        conn.execute(sa.text(f'DROP INDEX IF EXISTS "{idx}"'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_obs_cell_hazard_time'), 'satellite_observations', ['h3_cell', 'hazard_type', sa.literal_column('observed_at DESC')], unique=False)
    op.create_index(op.f('ml_features_wildfire_observed_at_idx'), 'ml_features_wildfire', [sa.literal_column('observed_at DESC')], unique=False)
    op.create_index(op.f('ml_features_heat_observed_at_idx'), 'ml_features_heat', [sa.literal_column('observed_at DESC')], unique=False)
    op.create_index(op.f('ml_features_flood_observed_at_idx'), 'ml_features_flood', [sa.literal_column('observed_at DESC')], unique=False)
    op.create_index(op.f('idx_flood_features_cell'), 'ml_features_flood', ['h3_cell', sa.literal_column('observed_at DESC')], unique=False)
    op.create_index(op.f('idx_locations_customer'), 'customer_locations', ['customer_id'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_scores_cell_hazard'), 'canonical_scores', ['h3_cell', 'hazard_type', 'scenario', 'time_horizon'], unique=False, postgresql_where='(valid_to IS NULL)')
    op.create_index(op.f('canonical_scores_scored_at_idx'), 'canonical_scores', [sa.literal_column('scored_at DESC')], unique=False)
    op.drop_column('canonical_scores', 'regulatory_fingerprint')
    op.drop_column('canonical_scores', 'compound_flag')
    op.drop_column('canonical_scores', 'ensemble_scores')
    op.drop_column('canonical_scores', 'score_velocity_48h')
    op.drop_column('canonical_scores', 'score_velocity_24h')
    op.drop_column('canonical_scores', 'score_velocity_6h')
    op.drop_column('canonical_scores', 'score_ci_upper')
    op.drop_column('canonical_scores', 'score_ci_lower')
    # ### end Alembic commands ###
