"""make_model_id_nullable

Revision ID: 80739a9ddc61
Revises: 72a3190412ba
Create Date: 2026-06-24 16:49:39.819378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '80739a9ddc61'
down_revision: Union[str, None] = '72a3190412ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('canonical_scores', 'model_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('canonical_scores', 'model_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
