"""A draft filing can be withdrawn — discarded under governance, never deleted.

A draft generated by mistake (wrong scope, wrong period) had no way out: the status CHECK had no terminal state for
"never filed, no longer wanted", and the live-slot index kept (framework, period, entity) blocked, so the right
filing could not be generated. 'withdrawn' is that terminal state:

  - reachable ONLY from draft or returned (nothing has been approved, attested or filed) — the guard trigger enforces
    it in the database, not just the service;
  - terminal: a withdrawn filing's status and frozen content never change again;
  - not live: it frees the slot (ux_reg_filing_live now excludes it, as it excludes superseded).

The frozen snapshot stays (report_snapshots is WORM); the row and its event history stay. A pending cell-override
proposal on the withdrawn filing is closed as 'withdrawn' too (its approval request is withdrawn with it).

Revision ID: filing_withdrawn_20260929
Revises: period_label_derived_20260929
"""
from typing import Sequence, Union

from alembic import op

revision: str = "filing_withdrawn_20260929"
down_revision: Union[str, None] = "period_label_derived_20260929"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_PROBE_ORG = "0bbe0bbe-0000-4000-8000-00000000f1d0"
REFUSAL_PROBE = {
    "setup": f"""INSERT INTO organizations (org_id, name, type, country) VALUES ('{_PROBE_ORG}', 'refusal probe', 'bank', 'DE');
                 INSERT INTO regulatory_filing (org_id, framework, period_end, period_label, status)
                 VALUES ('{_PROBE_ORG}', 'bank_tcfd', '2025-12-31', 'FY2025', 'withdrawn');""",
    "cleanup": f"""DELETE FROM regulatory_filing WHERE org_id = '{_PROBE_ORG}'; DELETE FROM organizations WHERE org_id = '{_PROBE_ORG}';""",
}

_FILING_STATUSES = "'draft','in_review','returned','approved','attested','submitted','accepted','rejected','superseded'"
_OVERRIDE_STATUSES = "'pending','approved','rejected','superseded'"
_LIVE_INDEX = """CREATE UNIQUE INDEX ux_reg_filing_live
    ON regulatory_filing (org_id, framework, period_end, COALESCE(entity_id, '00000000-0000-0000-0000-000000000000'::uuid))
    WHERE {where}"""

GUARD = """
CREATE OR REPLACE FUNCTION guard_filing_transition() RETURNS trigger AS $$
BEGIN
    -- withdrawn is terminal: the discarded draft keeps its status and frozen content for good
    IF OLD.status = 'withdrawn' THEN
        IF NEW.status <> 'withdrawn'
           OR NEW.snapshot_id IS DISTINCT FROM OLD.snapshot_id
           OR NEW.period_end <> OLD.period_end
           OR NEW.framework <> OLD.framework
           OR NEW.entity_id IS DISTINCT FROM OLD.entity_id THEN
            RAISE EXCEPTION 'filing % is withdrawn — it cannot change', OLD.filing_id;
        END IF;
    END IF;
    -- only a filing nothing has signed off may be withdrawn
    IF NEW.status = 'withdrawn' AND OLD.status NOT IN ('draft','returned','withdrawn') THEN
        RAISE EXCEPTION 'filing % is % — only a draft or returned filing can be withdrawn', OLD.filing_id, OLD.status;
    END IF;
    IF OLD.status IN ('submitted','accepted') THEN
        -- content is frozen once filed
        IF NEW.snapshot_id IS DISTINCT FROM OLD.snapshot_id
           OR NEW.period_end <> OLD.period_end
           OR NEW.framework <> OLD.framework THEN
            RAISE EXCEPTION 'filing % is % — its frozen content cannot change (restate via supersession)',
                            OLD.filing_id, OLD.status;
        END IF;
        -- status may only move forward: submitted→accepted, or either→superseded
        IF NEW.status <> OLD.status
           AND NOT (OLD.status = 'submitted' AND NEW.status = 'accepted')
           AND NEW.status <> 'superseded' THEN
            RAISE EXCEPTION 'filing % is % and can only be accepted or superseded, not changed to %',
                            OLD.filing_id, OLD.status, NEW.status;
        END IF;
    END IF;
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

# exactly as reg_filing_guard_fix_20260803 defined it
PRIOR_GUARD = """
CREATE OR REPLACE FUNCTION guard_filing_transition() RETURNS trigger AS $$
BEGIN
    IF OLD.status IN ('submitted','accepted') THEN
        -- content is frozen once filed
        IF NEW.snapshot_id IS DISTINCT FROM OLD.snapshot_id
           OR NEW.period_end <> OLD.period_end
           OR NEW.framework <> OLD.framework THEN
            RAISE EXCEPTION 'filing % is % — its frozen content cannot change (restate via supersession)',
                            OLD.filing_id, OLD.status;
        END IF;
        -- status may only move forward: submitted→accepted, or either→superseded
        IF NEW.status <> OLD.status
           AND NOT (OLD.status = 'submitted' AND NEW.status = 'accepted')
           AND NEW.status <> 'superseded' THEN
            RAISE EXCEPTION 'filing % is % and can only be accepted or superseded, not changed to %',
                            OLD.filing_id, OLD.status, NEW.status;
        END IF;
    END IF;
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


def upgrade() -> None:
    op.execute("ALTER TABLE regulatory_filing DROP CONSTRAINT regulatory_filing_status_check")
    op.execute(f"ALTER TABLE regulatory_filing ADD CONSTRAINT regulatory_filing_status_check "
               f"CHECK (status IN ({_FILING_STATUSES},'withdrawn'))")
    op.execute("DROP INDEX ux_reg_filing_live")
    op.execute(_LIVE_INDEX.format(where="status NOT IN ('superseded','withdrawn')"))
    op.execute("ALTER TABLE filing_cell_override DROP CONSTRAINT filing_cell_override_status_check")
    op.execute(f"ALTER TABLE filing_cell_override ADD CONSTRAINT filing_cell_override_status_check "
               f"CHECK (status IN ({_OVERRIDE_STATUSES},'withdrawn'))")
    op.execute(GUARD)


def downgrade() -> None:
    # the prior shape has no state for a withdrawn filing or override — refuse rather than rewrite what was recorded
    op.execute("""DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM regulatory_filing WHERE status = 'withdrawn')
                       OR EXISTS (SELECT 1 FROM filing_cell_override WHERE status = 'withdrawn') THEN
                      RAISE EXCEPTION 'withdrawn filings or overrides exist; the prior schema cannot represent them';
                    END IF;
                  END $$""")
    op.execute(PRIOR_GUARD)
    op.execute("ALTER TABLE filing_cell_override DROP CONSTRAINT filing_cell_override_status_check")
    op.execute(f"ALTER TABLE filing_cell_override ADD CONSTRAINT filing_cell_override_status_check "
               f"CHECK (status IN ({_OVERRIDE_STATUSES}))")
    op.execute("DROP INDEX ux_reg_filing_live")
    op.execute(_LIVE_INDEX.format(where="status <> 'superseded'"))
    op.execute("ALTER TABLE regulatory_filing DROP CONSTRAINT regulatory_filing_status_check")
    op.execute(f"ALTER TABLE regulatory_filing ADD CONSTRAINT regulatory_filing_status_check "
               f"CHECK (status IN ({_FILING_STATUSES}))")
