"""End to end, through the HTTP API: a draft generated by mistake is withdrawn under governance, and its slot is free.

  generate a draft → withdrawing without a real reason is refused → withdraw it (event + audit, snapshot kept) → it is
  no longer live (register shows it withdrawn, the calendar no longer counts it) → the same (framework, period, entity)
  generates again → a filed filing can never be withdrawn (service and database guard) → a withdrawn one never changes.

The API runs with its database session replaced by one rolled-back transaction (commits are flushes).
"""
from __future__ import annotations

import pytest
from sqlalchemy import text
from sqlalchemy.exc import DBAPIError

from services.governance.reporting_settings import upsert_reporting_settings
from tests.integration.conftest import login as _login
from tests.integration.test_intake_pipeline import BANK_ORG

pytestmark = pytest.mark.integration

PERIOD = "2093-12-31"          # a period no real filing uses, so the whole-organisation slot starts empty


def _generate(api, maker) -> dict:
    pf = api.get("/v1/filings/preflight?framework=bank_tcfd", headers=maker).json()
    assert pf["can_generate"], pf.get("existing_status")
    r = api.post("/v1/filings", headers=maker, json={"framework": "bank_tcfd", "confirm_token": pf["confirm_token"]})
    assert r.status_code == 201, r.text
    return r.json()


def test_withdraw_a_mistaken_draft_frees_its_slot(api):
    maker = _login(api, "admin@meridian.demo", "Demo!admin1")
    s = api.s
    admin = s.execute(text("SELECT user_id::text FROM users WHERE email = 'admin@meridian.demo'")).scalar()
    upsert_reporting_settings(s, BANK_ORG, {"reporting_period_end": PERIOD}, admin)

    # 1 · a draft for the slot; a second one is refused while it is live
    draft = _generate(api, maker)
    fid, snap = draft["filing_id"], s.execute(text("SELECT snapshot_id FROM regulatory_filing WHERE filing_id = :f"),
                                               {"f": draft["filing_id"]}).scalar()
    assert draft["status"] == "draft" and snap is not None
    assert api.get("/v1/filings/preflight?framework=bank_tcfd", headers=maker).json()["can_generate"] is False

    # 2 · a reason is required — missing, or too short to say anything
    assert api.post(f"/v1/filings/{fid}/withdraw", headers=maker, json={}).status_code == 422
    assert api.post(f"/v1/filings/{fid}/withdraw", headers=maker, json={"reason": "oops"}).status_code == 422
    assert api.post(f"/v1/filings/{fid}/withdraw", headers=maker, json={"reason": "          x"}).status_code == 409

    # a manual override is awaiting 4-eyes on the draft
    form = api.get(f"/v1/filings/{fid}/form", headers=maker).json()
    dp = next(d for g in form["groups"] if "datapoints" in g for d in g["datapoints"]
              if d.get("fmt") != "text" and isinstance(d.get("value"), (int, float)))
    ov = api.post(f"/v1/filings/{fid}/overrides", headers=maker,
                  json={"datapoint_key": dp["key"], "value": 1.0, "reason": "a correction"})
    assert ov.status_code == 201, ov.text

    # 3 · withdraw it: terminal status, a lifecycle event and an audit entry carrying the reason; the snapshot stays
    reason = "generated for the wrong scope"
    r = api.post(f"/v1/filings/{fid}/withdraw", headers=maker, json={"reason": reason})
    assert r.status_code == 200, r.text
    # the pending override is closed with it, and its approval request withdrawn (never decidable)
    assert s.execute(text("SELECT status FROM filing_cell_override WHERE override_id = CAST(:i AS uuid)"),
                     {"i": ov.json()["override_id"]}).scalar() == "withdrawn"
    assert tuple(s.execute(text("SELECT status, withdrawn_cause FROM approval_requests WHERE request_id = CAST(:i AS uuid)"),
                           {"i": ov.json()["approval_request_id"]}).one()) == ("withdrawn", "filing_withdrawn")
    assert r.json()["status"] == "withdrawn"
    ev = r.json()["events"][-1]
    assert (ev["from"], ev["to"], ev["action"], ev["detail"]["reason"]) == ("draft", "withdrawn", "withdraw", reason)
    audit = s.execute(text("""SELECT detail->>'reason' FROM access_audit_log
                              WHERE action = 'filing.withdraw' AND target_id = :f"""), {"f": fid}).scalar()
    assert audit == reason
    assert s.execute(text("SELECT snapshot_id FROM regulatory_filing WHERE filing_id = :f"), {"f": fid}).scalar() == snap
    assert s.execute(text("SELECT 1 FROM report_snapshots WHERE snapshot_id = :s"), {"s": snap}).scalar() == 1

    # 4 · no longer live: the register shows it as withdrawn; the calendar does not count it against the obligation
    reg = {f["filing_id"]: f["status"] for f in api.get("/v1/filings", headers=maker).json()["filings"]}
    assert reg[fid] == "withdrawn"
    obs = api.get("/v1/obligations", headers=maker).json()
    obs = obs.get("obligations", obs) if isinstance(obs, dict) else obs
    assert all(o.get("filing_id") != fid for o in obs)

    # 5 · the slot is free: the same framework / period / scope generates again
    again = _generate(api, maker)
    assert again["filing_id"] != fid and again["status"] == "draft"

    # 6 · a withdrawn filing never changes — not by the API, not in the database
    assert api.post(f"/v1/filings/{fid}/withdraw", headers=maker, json={"reason": reason}).status_code == 409
    assert api.post(f"/v1/filings/{fid}/submit-for-review", headers=maker).status_code == 409
    assert api.post(f"/v1/filings/{fid}/overrides", headers=maker,
                    json={"datapoint_key": dp["key"], "value": 2.0, "reason": "too late"}).status_code == 409
    with pytest.raises(DBAPIError, match="withdrawn"):
        with s.begin_nested():
            s.execute(text("UPDATE regulatory_filing SET status = 'draft' WHERE filing_id = :f"), {"f": fid})


def test_a_filed_filing_cannot_be_withdrawn(api):
    maker = _login(api, "admin@meridian.demo", "Demo!admin1")
    s = api.s
    filed = s.execute(text("""SELECT filing_id::text FROM regulatory_filing WHERE org_id = CAST(:o AS uuid)
                              AND status IN ('submitted', 'accepted') LIMIT 1"""), {"o": BANK_ORG}).scalar()
    assert filed, "the demo bank has a filed filing"
    r = api.post(f"/v1/filings/{filed}/withdraw", headers=maker, json={"reason": "trying to discard a filed report"})
    assert r.status_code == 409 and "restate" in r.json()["error"]["message"].lower()
    # the database refuses it too, whoever asks
    with pytest.raises(DBAPIError, match="only a draft or returned filing can be withdrawn"):
        with s.begin_nested():
            s.execute(text("UPDATE regulatory_filing SET status = 'withdrawn' WHERE filing_id = :f"), {"f": filed})
