"""Population export — the supervisor's analyses as one workbook, from the same services the screens use."""
from __future__ import annotations

import io
from datetime import datetime, timezone

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill
from openpyxl.utils import get_column_letter


def _sheet(wb: Workbook, title: str, header: list[str], rows: list[list]) -> None:
    ws = wb.create_sheet(title[:31])
    ws.append(header)
    for c in ws[1]:
        c.font = Font(bold=True); c.fill = PatternFill("solid", fgColor="E9EEF5")
    for r in rows:
        ws.append(["" if v is None else v for v in r])
    for i, h in enumerate(header, 1):
        ws.column_dimensions[get_column_letter(i)].width = min(60, max(12, len(str(h)) + 2, *(len(str(r[i - 1])) + 2 for r in rows[:200] if i - 1 < len(r))))
    ws.freeze_panes = "A2"


def population_workbook(*, regulator: str, profile: str, scenario: str, horizon: str, workflow: dict, benchmark: dict,
                        analytics: dict, requests: list[dict], generated_by: str) -> bytes:
    wb = Workbook()
    ws = wb.active; ws.title = "About"
    for row in [["Tellumen — supervised population export"], ["Supervisory body", regulator], ["Profile", profile],
                ["Basis", f"{scenario} · {horizon}"], ["Generated", datetime.now(timezone.utc).isoformat()], ["Generated by", generated_by],
                ["Note", "Every figure comes from the same engine and services the supervisory workspace shows. Cells without data are blank, never estimated."]]:
        ws.append(row)
    ws.column_dimensions["A"].width = 22; ws.column_dimensions["B"].width = 90
    _sheet(wb, "Population", ["Entity", "Sector", "Country", "Jurisdiction", "In profile", "Stage", "Filed", "Expected", "Book at high risk %", "High-risk flag",
                              "Lens gap %", "Open questions", "Site access", "Requests open", "Next action"],
           [[e["name"], e.get("sector_label"), e.get("country"), e.get("jurisdiction"), e.get("in_profile"), e.get("stage"), e.get("filed"), e.get("expected"),
             e.get("high_risk_share_pct"), e.get("high_risk_flag"), e.get("lens_gap_pct"), e.get("n_questions"), e.get("site_access"),
             (e.get("engagement") or {}).get("n_open"), (e.get("next") or {}).get("label")] for e in workflow.get("entities", [])])
    bench_rows = []
    for sec_key, sec in (benchmark.get("sectors") or {}).items():
        for m in sec.get("metrics", []):
            d = m.get("distribution") or {}
            for e in m.get("entities", []):
                bench_rows.append([sec.get("label") or sec_key, m["label"], m.get("unit"), e.get("name"), e.get("value"), e.get("flag"), e.get("percentile"),
                                   d.get("min"), d.get("p25"), d.get("median"), d.get("p75"), d.get("max"), d.get("n")])
    _sheet(wb, "Peer benchmark", ["Sector", "Metric", "Unit", "Entity", "Value", "Flag", "Percentile", "Min", "P25", "Median", "P75", "Max", "N"], bench_rows)
    conc = analytics.get("concentration") or {}
    total = float(conc.get("total_value_eur") or 0)
    _sheet(wb, "Concentration by region", ["Region", "Country", "Unit", "Sites", "Value €", "Share %", "Worst score", "Worst hazard", "Entities"],
           [[r.get("name"), r.get("country"), r.get("kind"), r.get("n_sites"), r.get("value_eur"),
             round(100.0 * float(r.get("value_eur") or 0) / total, 2) if total else None, r.get("max_score"), r.get("worst_hazard"), ", ".join(r.get("entities") or [])]
            for r in conc.get("by_region", [])])
    _sheet(wb, "Exposure by hazard", ["Headline hazard", "Assets", "Value €", "Of which High/Very high €"],
           [[h.get("hazard"), h.get("n"), h.get("value_eur"), h.get("high_value_eur")] for h in conc.get("by_hazard", [])])
    shift = analytics.get("scenario_shift") or {}
    _sheet(wb, "Scenario shift", ["Scenario", "Horizon", "Value €", "High-risk value €", "High-risk share %", "Projected share of high %"],
           [[c.get("scenario"), c.get("horizon"), c.get("value_eur"), c.get("high_risk_value_eur"), c.get("high_risk_share_pct"), c.get("projected_share_of_high_pct")] for c in shift.get("cells", [])])
    _sheet(wb, "Requests & findings", ["Entity", "Kind", "Title", "Status", "Severity", "Due", "Overdue", "Raised", "Closed"],
           [[r.get("entity"), r.get("kind_label"), r.get("title"), r.get("status_label"), r.get("severity"), r.get("due_date"), r.get("overdue"), (r.get("raised_at") or "")[:10], (r.get("closed_at") or "")[:10]] for r in requests])
    buf = io.BytesIO(); wb.save(buf)
    return buf.getvalue()
