"""The official regulator form — the same frozen datapoints arranged into the ACTUAL Annex / template
layout the regulator publishes, so a preparer sees the filing as it will be submitted, not just a flat list.

Each framework maps to the structure of its official form (SFDR RTS Annex I Table 1; the EU-Taxonomy
Article 8 GAR summary; the ESRS E1 disclosure requirements; the EIOPA/IFRS-S2 nat-cat table). The layout is
built from the merged datapoints (`dps` = key -> datapoint, already carrying any approved/pending override),
so a value cell references a datapoint KEY and the frontend renders it with the same value + manual/pending
flag + override control as the datapoint list. Descriptive cells are static official text. Figures are never
invented — a datapoint the snapshot doesn't carry renders as "—".
"""
from __future__ import annotations

from services.governance.reg_reference import reference


def _txt(s):
    return {"text": s}


def _num(s):
    """A right-aligned numeric text cell (for computed grid figures like Template 5)."""
    return {"text": s, "num": True}


def _cell(dps, key):
    """A value cell bound to a datapoint key — carries the merged datapoint (value + manual/pending) or a
    placeholder so the official row still appears when the snapshot has no figure for it."""
    d = dps.get(key)
    return {"dp": d} if d else {"dp": {"key": key, "label": "", "value": None, "fmt": "num",
                                       "unit": None, "source": "calculated", "note": None}}


def _pct_text(part, whole):
    if not isinstance(part, (int, float)) or not isinstance(whole, (int, float)) or not whole:
        return "—"
    return f"{round(part / whole * 100, 1)}%"


def _pretty_hazard(label: str) -> str:
    """Readable hazard name for the official-form label column (drought → Drought, soil_water → Soil water)."""
    s = (label or "").replace("_", " ").strip()
    return s[:1].upper() + s[1:] if s else s


# ── SFDR — RTS (EU) 2022/1288 Annex I (the PAI statement) ──────────────────────────────────────────────────
# Built to the ACTUAL Annex I template, not a summary. Table 1 = the 18 MANDATORY principal-adverse-impact
# indicators (14 investee-company + 2 sovereign/supranational + 2 real-estate), each with its verbatim
# "Metric" wording from the Annex; Tables 2 & 3 = the opt-in "additional" indicators (the filer selects at
# least one from each). Each row carries the Annex's own six columns: Adverse sustainability indicator ·
# Metric · Impact [reference period] · Impact [prior period] · Explanation · Actions taken/planned.
# The impact figure binds to the assembled datapoint (indicator.<n>); the prior period / explanation /
# actions columns bind to indicator.<n>.prior|expl|action so an override can populate them, else render "—".
_SFDR_TABLE1 = [
    ("Climate and other environment-related indicators", [
        ("Greenhouse gas emissions", [
            (1, "GHG emissions", "Scope 1, Scope 2 and Scope 3 GHG emissions and total GHG emissions"),
            (2, "Carbon footprint", "Carbon footprint"),
            (3, "GHG intensity of investee companies", "GHG intensity of investee companies"),
            (4, "Exposure to companies active in the fossil fuel sector",
                "Share of investments in companies active in the fossil fuel sector"),
            (5, "Share of non-renewable energy consumption and production",
                "Share of non-renewable energy consumption and non-renewable energy production of investee "
                "companies from non-renewable energy sources compared to renewable energy sources, expressed "
                "as a percentage of total energy sources"),
            (6, "Energy consumption intensity per high-impact climate sector",
                "Energy consumption in GWh per million EUR of revenue of investee companies, per high-impact "
                "climate sector"),
        ]),
        ("Biodiversity", [
            (7, "Activities negatively affecting biodiversity-sensitive areas",
                "Share of investments in investee companies with sites/operations located in or near to "
                "biodiversity-sensitive areas where activities of those investee companies negatively affect "
                "those areas"),
        ]),
        ("Water", [
            (8, "Emissions to water",
                "Tonnes of emissions to water generated by investee companies per million EUR invested, "
                "expressed as a weighted average"),
        ]),
        ("Waste", [
            (9, "Hazardous waste and radioactive waste ratio",
                "Tonnes of hazardous waste and radioactive waste generated by investee companies per million "
                "EUR invested, expressed as a weighted average"),
        ]),
    ]),
    ("Indicators for social and employee, respect for human rights, anti-corruption and anti-bribery matters", [
        (None, [
            (10, "Violations of UN Global Compact principles and OECD Guidelines for Multinational Enterprises",
                 "Share of investments in investee companies that have been involved in violations of the UNGC "
                 "principles or OECD Guidelines for Multinational Enterprises"),
            (11, "Lack of processes and compliance mechanisms to monitor compliance with UNGC / OECD Guidelines",
                 "Share of investments in investee companies without policies to monitor compliance with the "
                 "UNGC principles or OECD Guidelines or grievance/complaints-handling mechanisms to address "
                 "violations of the UNGC principles or OECD Guidelines"),
            (12, "Unadjusted gender pay gap", "Average unadjusted gender pay gap of investee companies"),
            (13, "Board gender diversity", "Average ratio of female to male board members in investee companies"),
            (14, "Exposure to controversial weapons (anti-personnel mines, cluster munitions, chemical and "
                 "biological weapons)",
                 "Share of investments in investee companies involved in the manufacture or selling of "
                 "controversial weapons"),
        ]),
    ]),
    ("Indicators applicable to investments in sovereigns and supranationals", [
        (None, [
            (15, "GHG intensity", "GHG intensity of investee countries"),
            (16, "Investee countries subject to social violations",
                 "Number of investee countries subject to social violations (absolute number and relative "
                 "number divided by all investee countries), as referred to in international treaties and "
                 "conventions, United Nations principles and, where applicable, national law"),
        ]),
    ]),
    ("Indicators applicable to investments in real estate assets", [
        (None, [
            (17, "Exposure to fossil fuels through real estate assets",
                 "Share of investments in real estate assets involved in the extraction, storage, transport "
                 "or manufacture of fossil fuels"),
            (18, "Exposure to energy-inefficient real estate assets",
                 "Share of investments in energy-inefficient real estate assets"),
        ]),
    ]),
]

# The six columns of the Annex I template, verbatim.
_SFDR_COLS = ["Adverse sustainability indicator", "Metric", "Impact (reference period)",
              "Impact (prior period)", "Explanation",
              "Actions taken, and actions planned and targets set for the next reference period"]


def _sfdr_annex(dps: dict) -> list[dict]:
    sections: list[dict] = []
    for theme, subgroups in _SFDR_TABLE1:
        rows: list[dict] = []
        for sub, inds in subgroups:
            if sub:
                rows.append({"type": "subheader", "label": sub})
            for n, name, metric in inds:
                rows.append({"type": "row", "cells": [
                    _txt(name), _txt(metric), _cell(dps, f"indicator.{n}"),
                    _cell(dps, f"indicator.{n}.prior"),
                    _txt((dps.get(f"indicator.{n}.expl") or {}).get("value") or "—"),
                    _txt((dps.get(f"indicator.{n}.action") or {}).get("value") or "—"),
                ]})
        sections.append({"title": f"Table 1 · {theme}", "columns": _SFDR_COLS, "rows": rows, "note": None})
    sections[0]["note"] = (
        "Statement on principal adverse impacts of investment decisions on sustainability factors "
        "(SFDR RTS (EU) 2022/1288, Annex I). Table 1 lists the 18 mandatory indicators; the impact figure is "
        "the frozen datapoint, and the prior-period / explanation / actions columns are completed at submission.")

    # Tables 2 & 3 — the opt-in "additional" indicators. The filer must select at least one from each; we
    # surface those the snapshot carries (keyed indicator.env.* / indicator.social.*), never fabricating a menu.
    def _extra(prefix, title, note):
        rows = []
        for k in sorted(dps):
            if k.startswith(prefix):
                d = dps[k]
                rows.append({"type": "row", "cells": [
                    _txt(d.get("label", "")), _txt(d.get("metric") or d.get("label", "")), {"dp": d},
                    _txt("—"), _txt(d.get("note") or "—"), _txt("—"),
                ]})
        if rows:
            sections.append({"title": title, "columns": _SFDR_COLS, "rows": rows, "note": note})

    _extra("indicator.env.", "Table 2 · Additional climate & environmental indicators (opt-in — select ≥1)",
           "Additional indicators for principal adverse impacts on sustainability factors — environmental "
           "(SFDR RTS Annex I, Table 2). At least one must be reported; those carried by this filing are shown.")
    _extra("indicator.social.", "Table 3 · Additional social indicators (opt-in — select ≥1)",
           "Additional indicators for principal adverse impacts — social and employee, human-rights, "
           "anti-corruption and anti-bribery (SFDR RTS Annex I, Table 3). At least one must be reported.")
    return sections


# ── EU-Taxonomy Article 8 (GAR summary) + PCAF financed emissions + TCFD physical-risk metrics ─────────────
def _located_annex(dps: dict) -> list[dict]:
    total = (dps.get("book.total_value_eur") or {}).get("value")
    sections: list[dict] = []

    # EU-Taxonomy Art. 8 — Green Asset Ratio summary template
    if any(k in dps for k in ("taxonomy.eligible_value_eur", "taxonomy.not_eligible_value_eur")):
        gar_rows = []
        for key, label in [("taxonomy.eligible_value_eur", "Taxonomy-eligible exposures"),
                           ("taxonomy.not_eligible_value_eur", "Not eligible"),
                           ("taxonomy.not_assessed_value_eur", "Not assessed / no data")]:
            d = dps.get(key)
            gar_rows.append({"type": "row", "cells": [
                _txt(label), _cell(dps, key), _txt(_pct_text((d or {}).get("value"), total)),
            ]})
        gar_rows.append({"type": "row", "cells": [_txt("Total covered assets"), _cell(dps, "book.total_value_eur"), _txt("100%")]})
        sections.append({
            "title": "EU Taxonomy · Article 8 — Green Asset Ratio (summary)",
            "columns": ["KPI", "Amount", "% of covered assets"], "rows": gar_rows,
            "note": "Eligibility KPI per Disclosures Delegated Act (EU) 2021/2178. Alignment (DNSH + minimum "
                    "safeguards) is disclosed in the full GAR templates.",
        })

    # PCAF financed emissions
    if any(k in dps for k in ("emissions.scope1", "emissions.total")):
        em_rows = [{"type": "row", "cells": [_txt(label), _cell(dps, key)]} for key, label in [
            ("emissions.scope1", "Scope 1"), ("emissions.scope2", "Scope 2"),
            ("emissions.scope3", "Scope 3 (financed)"), ("emissions.total", "Total financed emissions")]]
        sections.append({"title": "Financed emissions · PCAF (tCO₂e)", "columns": ["Scope", "tCO₂e"],
                         "rows": em_rows, "note": None})

    # TCFD metrics & targets — physical-risk exposure by hazard
    sections += _tcfd_physical_sections(dps)
    return sections


def _tcfd_physical_sections(dps: dict) -> list[dict]:
    """TCFD 'Metrics & targets' — physical-climate-risk exposure by hazard. Shared by the bank/insurer
    located annex and the REIT annex (a REIT's property book is scored the same way)."""
    haz_keys = sorted([k for k in dps if k.startswith("hazard.")], key=lambda k: -((dps[k].get("value")) or 0))
    haz_rows = []
    for key in ("book.value_at_risk_eur", "book.pct_value_at_risk", "book.total_discounted_value_eur"):
        if key in dps:
            haz_rows.append({"type": "row", "cells": [_txt(dps[key]["label"]), _cell(dps, key)]})
    if haz_keys:
        haz_rows.append({"type": "subheader", "label": "Value exposed at High+ by hazard"})
        for key in haz_keys:
            haz_rows.append({"type": "row", "cells": [_txt(_pretty_hazard(dps[key].get("label") or key.split(".", 1)[1])), _cell(dps, key)]})
    if not haz_rows:
        return []
    return [{"title": "TCFD · Metrics & targets — physical climate risk",
             "columns": ["Metric", "Value"], "rows": haz_rows, "note": None}]


# ── REIT — EU-Taxonomy Article 8 NON-FINANCIAL KPI templates (Turnover/CapEx/OpEx) + TCFD physical ──────────
# Correctness: a REIT is a NON-FINANCIAL undertaking. It does NOT file a Green Asset Ratio (that is credit-
# institutions only, Del. Reg. 2021/2178 Annex V). It files the three Taxonomy KPIs — Turnover, CapEx, OpEx —
# on the Annex II template. The KPI figures are financial-statement data (customer), so we render the exact
# template row structure and declare them customer-supplied; the property book's eligible activity and our
# physical-climate-risk assessment (which feeds the Climate-Change-Adaptation objective and its DNSH test) are
# surfaced explicitly. Nothing is fabricated.
_TAXONOMY_KPI_ROWS = [
    ("A. Taxonomy-eligible activities", True),
    ("A.1 Environmentally sustainable (Taxonomy-aligned)", False),
    ("       of which enabling", False),
    ("       of which transitional", False),
    ("A.2 Taxonomy-eligible but not environmentally sustainable (not aligned)", False),
    ("Total (A.1 + A.2)", False),
    ("B. Taxonomy-non-eligible activities", True),
    ("Total (A + B)", False),
]


def _reit_annex(dps: dict, payload: dict) -> list[dict]:
    sections: list[dict] = []
    total = (dps.get("book.total_value_eur") or {}).get("value")
    elig = (dps.get("taxonomy.eligible_value_eur") or {}).get("value")

    # The three KPI templates (Annex II). Figures are the undertaking's Turnover/CapEx/OpEx proportions —
    # financial-statement data we do not hold — so every cell is declared customer-supplied ("—").
    kpi_rows = []
    for label, is_header in _TAXONOMY_KPI_ROWS:
        if is_header:
            kpi_rows.append({"type": "subheader", "label": label})
        else:
            kpi_rows.append({"type": "row", "cells": [_txt(label), _txt("—"), _txt("—"), _txt("—")]})
    sections.append({
        "title": "EU Taxonomy · Article 8 — Turnover / CapEx / OpEx KPIs (non-financial undertaking)",
        "columns": ["Proportion of", "Turnover KPI", "CapEx KPI", "OpEx KPI"], "rows": kpi_rows,
        "note": "Del. Reg. (EU) 2021/2178, Annex II. A REIT files these three KPIs — NOT a Green Asset Ratio "
                "(the GAR is for credit institutions only). The proportions are financial-statement figures "
                "(turnover, capital and operating expenditure) supplied by the undertaking. The eligible economic "
                "activity for a property book is 'acquisition and ownership of buildings' (Taxonomy 7.7); alignment "
                "additionally needs the technical screening criteria, DNSH and minimum safeguards.",
    })

    # Where OUR data plugs in: the physical-climate-risk assessment IS the evidence for the Climate-Change-
    # Adaptation objective and its DNSH check. Surfaced on an asset (book-value) basis — informational, clearly
    # NOT the KPI basis — so the preparer sees what we contribute without conflating the two.
    if isinstance(elig, (int, float)) and isinstance(total, (int, float)) and total:
        sections.append({
            "title": "Property book — Taxonomy-eligible activity & adaptation evidence (asset basis, informational)",
            "columns": ["Measure", "Amount", "% of book"], "rows": [
                {"type": "row", "cells": [_txt("Property book eligible for activity 7.7 (acquisition & ownership of buildings)"),
                                          _cell(dps, "taxonomy.eligible_value_eur"), _txt(_pct_text(elig, total))]},
                {"type": "row", "cells": [_txt("Total property book"), _cell(dps, "book.total_value_eur"), _txt("100%")]},
            ],
            "note": "Asset-value basis — informational, NOT the Turnover/CapEx/OpEx KPI basis above. Our physical-"
                    "climate-risk assessment (see TCFD section) is the evidence base for the Climate-Change-"
                    "Adaptation substantial-contribution and the 'do no significant harm to adaptation' criterion.",
        })

    # TCFD physical-risk — the property book scored by hazard (genuinely computed by our engine).
    sections += _tcfd_physical_sections(dps)
    return sections


def _eur(v):
    """Readable euro for a computed annex cell (values are already in EUR)."""
    if not isinstance(v, (int, float)):
        return "—"
    n = float(v)
    if n == 0:
        return "€0"
    if abs(n) >= 1e9:
        return f"€{n / 1e9:.2f}bn"
    if abs(n) >= 1e6:
        return f"€{n / 1e6:.1f}m"
    if abs(n) >= 1e3:
        return f"€{round(n / 1e3):,}k"
    return f"€{round(n):,}"


# ── EBA Pillar 3 ESG (ITS 2022/2453): Template 5 physical risk + GAR summary + Scope-3 for transition ─────
def _p3esg_annex(dps: dict, payload: dict) -> list[dict]:
    total = (dps.get("book.total_value_eur") or {}).get("value")
    sections: list[dict] = []
    assets = (payload or {}).get("assets") or []

    # Template 1 — banking-book transition risk by NACE sector (ITS 2022/2453, Annex XXXIX). Computed columns:
    # gross carrying amount + financed emissions (Scope 1–3) + of-which Scope 3; credit-quality/alignment/maturity
    # columns are customer-supplied (declared).
    if assets:
        from services.governance.pillar3_templates import template1_grid
        g1 = template1_grid(assets)
        t1_rows = []
        for r in g1["rows"] + [g1["total"]]:
            lbl = "TOTAL" if r["section"] == "TOTAL" else f"{r['section']} · {r['label']}"
            t1_rows.append({"type": "row", "cells": [
                _txt(lbl), _num(_eur(r["gross"])), _num(f"{r['fin_emissions']:,}"), _num(f"{r['scope3']:,}")]})
        sections.append({"title": "Template 1 — Banking book · climate-change transition risk (ITS 2022/2453, Annex XXXIX)",
                         "columns": ["Sector (NACE)", "Gross carrying amount", "Financed emissions Scope 1–3 (tCO₂e)", "of which Scope 3 (tCO₂e)"],
                         "rows": t1_rows,
                         "note": g1["basis"] + " Customer-supplied columns not shown: " + " · ".join(g1["customer_columns"]) + "."})

    # Template 3 — transition-risk ALIGNMENT METRICS (ITS 2022/2453, Annex XL §38–41): per IEA sector, the
    # portfolio CO₂-intensity + its distance to the IEA NZE2050 2030 target. Gross amount + benchmark + distance
    # computed by Tellumen; the counterparty intensity is a vendor/counterparty feed (shown 'pending' until fed).
    if assets:
        from services.governance.transition_alignment import template3_grid
        g3 = template3_grid(assets)
        if g3["rows"]:
            t3_rows = []
            for r in g3["rows"]:
                cur = f'{r["current_intensity"]} {r["unit"]}' if r["current_intensity"] is not None else "pending vendor feed"
                tgt = f'{r["iea_2030"]} {r["unit"]}' if r["iea_2030"] is not None else "pending IEA ingest"
                dist = f'{r["distance_pct"]}%' if r["distance_pct"] is not None else "—"
                t3_rows.append({"type": "row", "cells": [
                    _txt(f'{r["label"]} · {r["metric"]}'), _num(_eur(r["gross"])), _num(cur), _num(tgt), _num(dist)]})
            sections.append({"title": "Template 3 — Banking book · transition risk · alignment metrics (ITS 2022/2453, Annex XL)",
                             "columns": ["Sector · IEA metric", "Gross carrying amount", "Portfolio intensity", "IEA NZE2050 2030 target", "Distance"],
                             "rows": t3_rows,
                             "note": g3["formula"] + ". " + g3["source"] + " Customer/vendor input: " + g3["customer_input"]})

    # Template 4 — exposures to the top-20 carbon-intensive firms (ITS 2022/2453, Annex XL §42–44).
    if assets:
        from services.governance.transition_alignment import template4_top20
        g4 = template4_top20(assets)
        if g4["matched_count"]:
            t4_rows = [{"type": "row", "cells": [_txt(r["firm"]), _num(_eur(r["gross"]))]} for r in g4["rows"]]
        else:
            t4_rows = [{"type": "row", "cells": [_txt("No counterparty matched the top-20 carbon-majors list"), _num(_eur(0))]}]
        sections.append({"title": "Template 4 — Banking book · exposures to the top-20 carbon-intensive firms (ITS 2022/2453, Annex XL)",
                         "columns": ["Counterparty (Carbon Majors)", "Gross carrying amount"], "rows": t4_rows,
                         "note": f'Matched {g4["matched_count"]} of the {g4["list_size"]}-firm list · total exposure {_eur(g4["total_exposure"])}. ' + g4["source"]})

    # Template 5 — banking-book physical-risk exposure, built to the ACTUAL ITS 2022/2453 grid:
    # rows = NACE section; columns = gross carrying amount + of-which physical-risk-sensitive + chronic/acute/both.
    if assets:
        from services.governance.pillar3_templates import template5_grid
        grid = template5_grid(assets)
        cols = ["Sector (NACE)", "Gross carrying amount", "of which physical-risk-sensitive",
                "of which chronic", "of which acute", "of which chronic + acute"]
        t5_rows = []
        for r in grid["rows"]:
            t5_rows.append({"type": "row", "cells": [
                _txt(f"{r['section']} · {r['label']}"), _num(_eur(r["gross"])), _num(_eur(r["sensitive"])),
                _num(_eur(r["chronic"])), _num(_eur(r["acute"])), _num(_eur(r["both"]))]})
        t = grid["total"]
        t5_rows.append({"type": "row", "cells": [
            _txt("TOTAL"), _num(_eur(t["gross"])), _num(_eur(t["sensitive"])),
            _num(_eur(t["chronic"])), _num(_eur(t["acute"])), _num(_eur(t["both"]))]})
        sections.append({"title": "Template 5 — Banking book · climate-change physical risk (ITS 2022/2453, Annex XXXIX)",
                         "columns": cols, "rows": t5_rows,
                         "note": grid["basis"] + " Customer-supplied columns not shown: " + " · ".join(grid["customer_columns"]) + "."})
    else:
        # fallback for a snapshot without the per-asset book: the earlier by-hazard summary
        haz_keys = sorted([k for k in dps if k.startswith("hazard.")], key=lambda k: -((dps[k].get("value")) or 0))
        t5_rows = []
        for key in ("book.total_value_eur", "book.value_at_risk_eur", "book.pct_value_at_risk"):
            if key in dps:
                t5_rows.append({"type": "row", "cells": [_txt(dps[key]["label"]), _cell(dps, key)]})
        for key in haz_keys:
            t5_rows.append({"type": "row", "cells": [_txt(_pretty_hazard(dps[key].get("label") or key.split(".", 1)[1])), _cell(dps, key)]})
        if t5_rows:
            sections.append({"title": "Template 5 — Banking book · climate-change physical risk",
                             "columns": ["Exposure metric", "Amount (€)"], "rows": t5_rows,
                             "note": "Physical-risk exposure per ITS (EU) 2022/2453 (per-asset book unavailable for the sector grid)."})

    # GAR (Templates 6–8) — Green Asset Ratio by counterparty class, built to the ITS grid: gross carrying
    # amount, Taxonomy-eligible + Taxonomy-aligned per counterparty, the covered-assets denominator (excl.
    # general governments, Art. 7) and the GAR ratio on stock. Computed from the per-asset taxonomy_status.
    if assets:
        from services.governance.pillar3_templates import gar_grid
        gg = gar_grid(assets)
        # When the book is classified only to eligibility (no positions carry an 'aligned' status), the aligned
        # figure is a floor, not a determined zero — show it as pending the technical screening, not a bare €0
        # that reads as "broken". A real aligned figure (any position screened) renders as the euro amount.
        align_pending = gg["aligned"] == 0 and gg["eligible"] > 0
        _aligned_cell = lambda v: _txt("pending screening") if align_pending else _num(_eur(v))
        gar_rows = []
        for r in gg["rows"]:
            note = " (excluded from covered assets)" if r["counterparty"] == "General governments" else ""
            gar_rows.append({"type": "row", "cells": [
                _txt(r["counterparty"] + note), _num(_eur(r["gross"])), _num(_eur(r["eligible"])), _aligned_cell(r["aligned"])]})
        gar_rows.append({"type": "row", "cells": [
            _txt("Covered assets (GAR denominator · excl. general governments)"),
            _num(_eur(gg["covered_assets"])), _num(_eur(gg["eligible"])), _aligned_cell(gg["aligned"])]})
        gar_rows.append({"type": "row", "cells": [
            _txt("Green Asset Ratio — on stock"), _txt("—"),
            _num(f'{gg["pct_eligible"]}% eligible' if gg["pct_eligible"] is not None else "—"),
            _txt("pending screening") if align_pending else
            _num(f'{gg["gar_stock_pct"]}% GAR' if gg["gar_stock_pct"] is not None else "—")]})
        note = gg["basis"] + " Customer-supplied / not shown: " + " · ".join(gg["customer_columns"]) + "."
        if align_pending:
            note += (" This book is classified to Taxonomy ELIGIBILITY; the aligned figure and GAR await the "
                     "technical-screening-criteria + DNSH confirmation, so both are shown as pending, not zero.")
        sections.append({"title": "Templates 6–8 — Green Asset Ratio by counterparty (ITS 2022/2453 · Del. Reg. 2021/2178)",
                         "columns": ["Counterparty class", "Gross carrying amount", "Taxonomy-eligible", "Taxonomy-aligned"],
                         "rows": gar_rows, "note": note})
    elif any(k in dps for k in ("taxonomy.eligible_value_eur", "taxonomy.not_eligible_value_eur")):
        # fallback (no per-asset book): the flat eligibility summary
        gar_rows = []
        for key, label in [("taxonomy.eligible_value_eur", "Taxonomy-eligible exposures"),
                           ("taxonomy.not_eligible_value_eur", "Not eligible"),
                           ("taxonomy.not_assessed_value_eur", "Not assessed / no data")]:
            gar_rows.append({"type": "row", "cells": [_txt(label), _cell(dps, key), _txt(_pct_text((dps.get(key) or {}).get("value"), total))]})
        sections.append({"title": "Green Asset Ratio (Templates 6–8) — eligibility",
                         "columns": ["KPI", "Amount", "% of covered assets"], "rows": gar_rows,
                         "note": "Eligibility numerator; alignment (DNSH + minimum safeguards) is disclosed in the full GAR templates."})

    # Template 10 — other climate-change-mitigating actions NOT covered by the EU Taxonomy (green/sustainability
    # bonds and specialised green lending). This is a qualitative template on instruments outside the Taxonomy
    # scope, so its rows are the undertaking's own instrument register — declared customer-supplied, never faked.
    if assets:
        t10_cols = ["Type of financial instrument", "Type of counterparty", "Gross carrying amount",
                    "Type of risk mitigated", "Qualitative information on the mitigating action"]
        sections.append({
            "title": "Template 10 — Other climate-change-mitigating actions not covered by the EU Taxonomy (ITS 2022/2453)",
            "columns": t10_cols, "rows": [
                {"type": "subheader", "label": "Bonds (banking book)"},
                {"type": "row", "cells": [_txt("Green / sustainability / sustainability-linked bonds"),
                                          _txt("—"), _txt("—"), _txt("—"), _txt("—")]},
                {"type": "subheader", "label": "Loans (banking book)"},
                {"type": "row", "cells": [_txt("Specialised green / sustainability-linked lending"),
                                          _txt("—"), _txt("—"), _txt("—"), _txt("—")]},
            ],
            "note": "ITS (EU) 2022/2453, Template 10. Captures instruments supporting the transition that are "
                    "NOT reflected in the Green Asset Ratio (i.e. outside the EU Taxonomy) — the undertaking's "
                    "own register of green/sustainability bonds and specialised green lending, with the nature of "
                    "each mitigating action. Instrument type is not held on the golden-source book, so these rows "
                    "are completed by the preparer at filing.",
        })

    # Scope-3 financed emissions — only as a fallback when the per-asset book is unavailable (otherwise the
    # Template 1 grid above already carries financed emissions by NACE sector).
    if not assets and any(k in dps for k in ("emissions.scope3", "emissions.total")):
        em_rows = [{"type": "row", "cells": [_txt(label), _cell(dps, key)]} for key, label in [
            ("emissions.scope3", "Scope 3 (financed) emissions"), ("emissions.total", "Total financed emissions")]]
        sections.append({"title": "Transition risk — financed emissions (PCAF, tCO₂e)", "columns": ["Scope", "tCO₂e"],
                         "rows": em_rows, "note": "Counterparty Scope-3 basis for the transition-risk templates (Templates 1–4)."})
    return sections


# ── ESRS / generic — present the reported datapoints in the standard's disclosure-requirement grouping ─────
def _generic_annex(dps: dict, groups: list[dict]) -> list[dict]:
    sections = []
    for g in groups:
        rows = [{"type": "row", "cells": [_txt(d.get("label", "")), {"dp": d}]} for d in g.get("datapoints", [])]
        if rows:
            sections.append({"title": g.get("group", "Disclosure"), "columns": ["Datapoint", "Value"],
                             "rows": rows, "note": None})
    return sections


def build_annex(framework: str, dps: dict, groups: list[dict], payload: dict | None = None) -> dict | None:
    """Assemble the official-form layout for a framework from its merged datapoints. `dps` is key -> merged
    datapoint; `groups` is the datapoint-list grouping (used for the generic/ESRS fallback); `payload` is the
    raw frozen snapshot, used where an official template is a computed GRID (Pillar 3 Template 5) not flat cells."""
    if framework == "sfdr_pai":
        sections = _sfdr_annex(dps)
    elif framework == "bank_p3esg":
        sections = _p3esg_annex(dps, payload or {})
    elif framework == "reit_tcfd":
        sections = _reit_annex(dps, payload or {})
    elif framework in ("bank_tcfd", "insurer_climate"):
        sections = _located_annex(dps)
    else:
        sections = _generic_annex(dps, groups)
    if not sections:
        return None
    ref = reference(framework) or {}
    return {
        "official_name": ref.get("official_name", framework),
        "authority": ref.get("authority"),
        "official_form": ref.get("official_form"),
        "legal_basis": ref.get("legal_basis"),
        "form_url": ref.get("form_url"),
        "sections": sections,
    }
