"""SFDR PAI statement against its specification (Delegated Regulation (EU) 2022/1288, Annex I) — run 2 of the route.

  * Table 1 is rendered row for row from the spec: GHG emissions as its Scope 1 / 2 / 3 / total rows, in printed order
  * adopted Table 2 / 3 indicators appear under 'Other indicators', with their official row number and wording
  * the opt-in catalogue is the spec's rows (keyed on table + row), with the aggregation each metric's wording needs
  * the diff to the ESAs draft reads a renumbering as a move; the draft never governs
"""
import services.regspec as R
from services.governance.filing_annex import build_annex
from services.governance.filing_form import build_form
from services.governance.sfdr_binding import BINDING, optional_catalog

SPEC = R.load("sfdr_pai", "rts_2022_1288")

PAYLOAD = {
    "indicators": [{"number": 1, "metric": "GHG emissions", "unit": "tCO₂e", "coverage_pct": 90.0,
                    "value": {"scope_1": 100.0, "scope_2": 20.0, "scope_3": 300.0, "total": 420.0}},
                   {"number": 2, "metric": "Carbon footprint", "unit": "tCO₂e/€M", "value": 12.5}],
    "sovereign_indicators": [{"number": 15, "metric": "GHG intensity of investee countries", "value": 210.0}],
    "additional_indicators": {"indicators": [
        {"key": "t2_13", "table": 2, "row": "13", "name": "Non-recycled waste ratio", "unit": "t", "value": 2.5,
         "metric": "Tonnes of non-recycled waste generated by investee companies per million EUR invested, expressed as a weighted average"},
        {"key": "t3_8", "table": 3, "row": "8", "name": "Excessive CEO pay ratio", "unit": "ratio", "value": 48.0,
         "metric": "Average ratio …"}], "missing": []},
}


def _annex(payload):
    groups = build_form("sfdr_pai", payload)
    dps = {d["key"]: d for g in groups for d in g["datapoints"]}
    return build_annex("sfdr_pai", dps, groups, payload), dps


def test_table1_is_the_spec_row_for_row():
    a, dps = _annex(PAYLOAD)
    rows = [r for s in a["sections"] if s["key"].startswith("sfdr_t1_") for r in s["rows"] if r["type"] == "row"]
    assert [r["cells"][1]["text"] for r in rows] == [x["label"].split(" > ")[-1] for x in R.template(SPEC, "T1")["rows"]]
    assert [r["cells"][2]["dp"]["value"] for r in rows[:4]] == [100.0, 20.0, 300.0, 420.0]    # Scope 1, 2, 3, total
    assert a["sections"][0]["columns"] == [c["label"] for c in R.template(SPEC, "T1")["columns"]]
    assert "2022/1288" in a["legal_basis"]                                     # frozen before specs: 2022/1288


def test_adopted_indicators_carry_their_official_row():
    a, dps = _annex(PAYLOAD)
    other = next(s for s in a["sections"] if s["key"] == "sfdr_other")
    labels = [r["cells"][0]["text"] for r in other["rows"] if r["type"] == "row"]
    assert labels == ["13. Non-recycled waste ratio", "8. Excessive CEO pay ratio"]
    assert dps["additional.t2_13"]["value"] == 2.5


def test_the_optin_catalogue_is_the_spec():
    cat = optional_catalog(SPEC)
    assert cat["t2_13"]["agg"] == "per_meur" and "per million EUR invested" in cat["t2_13"]["metric"]
    assert "threatened species" in cat["t2_14_1"]["metric"]
    assert "t2_5" not in cat and "t3_18" not in cat                          # a breakdown / a sovereign row: not offered
    offered = [(t, k) for t in ("T2", "T3") for k, v in BINDING[t]["rows"].items() if v != "n/a"]
    assert len(cat) == len(offered)


def test_the_esas_draft_is_a_template_change_read_as_moves():
    d = R.diff(SPEC, R.load("sfdr_pai", "esas_jc_2023_55_draft"))
    assert d["kind"] == "template change"
    t3 = next(c for c in d["changed"] if c["id"] == "T3")
    assert {"from": "11", "to": "16"} in [{"from": m["from"], "to": m["to"]} for m in t3["rows"]["moved"]]
    assert R.governing("sfdr_pai", period_end="2030-12-31")["version"] == "rts_2022_1288"
